spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mackerelcmslike_db?serverTimezone=UTC&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Rootoorn

  sql:
    init:
      platform: mysql
      mode: always

  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

#springdoc:
#  default-produces-media-type: application/json
